### ISSUE TITLE
Gosling Emacs source code

### ISSUE THREAD

**Issue by larsbrinkhoff** [jhallen/joe-editor#2]
You were [asking about Gosling Emacs source code](http://comp.editors.narkive.com/a1xVkz8E/gosling-emacs-source):

> Does anyone have a copy of Gosling's EMACS C source code? I had this a long
> time ago, but I've lost it. I can't find it anywhere on the net (it was
> withdrawn from the public domain, but surely there must be old versions
> around).

Yesterday, I got tarballs from Brian Reid, and copied them here with James Gosling's blessing: 

https://github.com/larsbrinkhoff/emacs-history/tree/sources/reid.org/%7Ebrian/misc

The 1999 copy has RCS history going back to 1986.

**Comment by jhallen** [comment]
Wow, nice!

Maybe I will fix it to compile on recent machines...

The notice in the Installation file is interesting:

"Please remember that Emacs is copyrighted.  You are free to use Emacs
internally, but you are not free to redistribute it.  If someone is
interested in obtaining a copy of Emacs, refer them to me:

```
                    James Gosling           [Gosling@CMUA]
                    Computer Science
                    Carnegie-Mellon University
                    Pittsburgh PA
                    15213"
```

**Comment by larsbrinkhoff** [comment]
Right.  I got permission to publish the tarballs from James Gosling.  But if some people actually want to use it, the copyright situation should be cleared first.

**Comment by neozeed** [comment]
ftp://ftp.informatik.uni-stuttgart.de/pub/cm/dec/decus/emacs.tap

/* Current Emacs version */
char version[] = "Emacs #264 of Mon May 16";
   containing Emaces */

and later on:
Copyright (c) 1983 James Gosling

This is apparently Gosling Emacs from 1984 tape.  The decus tape label is :
UniPress Software Inc.
PRODUCT:  EMACS SCREEN EDITOR
VAX/SUN UNIX 4.2 Source
(C)1983  tar  S/N # 1054   7/84

**Comment by larsbrinkhoff** [comment]
Thanks @neozeed, I snarfed it.  What tape format is it?

**Comment by neozeed** [comment]
I would assume with the tap extension it may be something like the SIMH tape format.  I just ran strings against it, and it looks like tar inside.  the C is perfectly legible if you want to take the dozens of house to copy out the files one at a time.... . :\

**Comment by larsbrinkhoff** [comment]
No, I can probably figure it out.  I just thought you knew already, in which case I wouldn't need to guess.

**Comment by neozeed** [comment]
I found an old program to extract a file from a tap.  I forget where I found it, but I just shoved it in a repo.

https://github.com/neozeed/detap

I think it may be short reading at the end of emacs.doc , although I haven't verified.  but the rest of it sure looks fine.  Last source change is:

28/06/1984  05:18 PM            23,572 mchan.c

And the directory has this as emacs 4.2

**Comment by larsbrinkhoff** [comment]
Yes, the tap file is truncated or malformed.  Still, cool find!

**Comment by neozeed** [comment]
If it counts for anything, I found another far more elaborate un-tap program, they both gave the same output.  

C:\Users\jason\Downloads>md5 emacs_tap2file.001
948abc3bab419b669976936eeb74827d emacs_tap2file.001

C:\Users\jason\Downloads>md5 emacs.tar
948abc3bab419b669976936eeb74827d emacs.tar

If I come across any other emacs stuff in my journeys's I'll be sure to give you a shout!

**Comment by larsbrinkhoff** [comment]
Thanks!

I looked at a hexdump, and it's clear that the last block isn't right.  There's a block length field, but no data.  Also, the last file is truncated mid-sentence.
